sudo: required

services:

  - docker


before_install:
  - docker build -t ImranBhabra/reactapp-test -f ./client/Dockerfile.dev ./
script:

  - docker run ImranBhabrareactapp-test npm test -- --coverage


after_success:

  - docker build -t ImranBhabra/reactapp-client ./client

  - docker build -t ImranBhabra/reactapp-nginx ./nginx

  - docker build -t ImranBhabra/reactapp-server ./server

  - docker build -t ImranBhabra/reactapp-worker ./worker
  
# Log in to the docker CLI

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
 
# Take those images and push them to Docke hub

  - docker push ImranBhabra/reactapp-client

  - docker push ImranBhabra/reactapp-nginx

  - docker push ImranBhabra/reactapp-server

  - docker push ImranBhabra/reactapp-worker

