sudo: required

services:

  - docker


before_install:
  - docker build -t ImranBhabra/multi-docker-test -f ./client/Dockerfile.dev ./
script:

  - docker run ImranBhabrareactapp-test npm test -- --coverage


after_success:

  - docker build -t ImranBhabra/multi-docker-client ./client

  - docker build -t ImranBhabra/multi-docker-nginx ./nginx

  - docker build -t ImranBhabra/multi-docker-server ./server

  - docker build -t ImranBhabra/multi-docker-worker ./worker
  
# Log in to the docker CLI

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
 
# Take those images and push them to Docke hub

  - docker push ImranBhabra/multi-docker-client

  - docker push ImranBhabra/multi-docker-nginx

  - docker push ImranBhabra/multi-docker-server

  - docker push ImranBhabra/multi-docker-worker

