language: generic
sudo: required

services:

  - docker


before_install:

  - docker build -t bhabra/multi-docker -f ./client/Dockerfile.dev ./client
script:

  - docker run bhabra/multi-docker npm test -- --coverage


after_success:

  - docker build -t bhabra/multi-client ./client

  - docker build -t bhabra/multi-nginx ./nginx

  - docker build -t bhabra/multi-server ./server

  - docker build -t bhabra/multi-worker ./worker
  
# Log in to the docker CLI

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
 
# Take those images and push them to Docke hub

  - docker push bhabra/multi-client

  - docker push bhabra/multi-nginx

  - docker push bhabra/multi-server

  - docker push bhabra/multi-worker

