sudo: required

services:

  - docker


before_install:
  - docker build -t bhabra/react-test -f ./client/Dockerfile.dev ./
script:

  - docker run bhabra/react-test npm test -- --coverage


after_success:

  - docker build -t bhabra/multi-client ./client

  - docker build -t bhabra/react-test/multi-nginx ./nginx

  - docker build -t bhabra/react-test/multi-server ./server

  - docker build -t bhabra/react-test/multi-worker ./worker
  
# Log in to the docker CLI

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
 
# Take those images and push them to Docke hub

  - docker push bhabra/react-test/multi-client

  - docker push bhabra/react-test/multi-nginx

  - docker push bhabra/react-test/multi-server

  - docker push bhabra/react-test/multi-worker

